// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJvTqsdzk48j5MFIN7X2GSNgMas78s_K4',
    appId: '1:815005194599:web:11da02aeec1d334a8af7c2',
    messagingSenderId: '815005194599',
    projectId: 'music-app-193ce',
    authDomain: 'music-app-193ce.firebaseapp.com',
    storageBucket: 'music-app-193ce.appspot.com',
    measurementId: 'G-NGJ20WCP82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Hx4n6R_k44_RdsrbOdVMK47b9bBWKCI',
    appId: '1:815005194599:android:90fda7c1bead7e258af7c2',
    messagingSenderId: '815005194599',
    projectId: 'music-app-193ce',
    storageBucket: 'music-app-193ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVX4i-ixRMSuZ5TMWznxtalA5wPjdNs6c',
    appId: '1:815005194599:ios:d0a2433b920362418af7c2',
    messagingSenderId: '815005194599',
    projectId: 'music-app-193ce',
    storageBucket: 'music-app-193ce.appspot.com',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVX4i-ixRMSuZ5TMWznxtalA5wPjdNs6c',
    appId: '1:815005194599:ios:f0777ec3018cd3f88af7c2',
    messagingSenderId: '815005194599',
    projectId: 'music-app-193ce',
    storageBucket: 'music-app-193ce.appspot.com',
    iosBundleId: 'com.example.musicApp.RunnerTests',
  );
}
